### ISSUE TITLE
failed to compile 

### ISSUE THREAD

**Issue by bbrunaud** [Argonne-National-Laboratory/DSP#10]
Hello

I tried to compile DSP today and the compilation failed. The output is below. The system is Linux Mint 17 (based on Ubuntu 14.04)

---
[ 83%] Building CXX object src/CMakeFiles/Dsp.dir/Solver/DualDecomp/DdDriverMpi.cpp.o
/tmp/DSP/src/Solver/DualDecomp/DdDriverMpi.cpp: In constructor ‘DdDriverMpi::DdDriverMpi(DspParams*, DecModel*, MPI_Comm)’:
/tmp/DSP/src/Solver/DualDecomp/DdDriverMpi.cpp:22:36: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘MPI_Comm {aka ompi_communicator_t*}’ [-Wformat=]
  DSPdebugMessage("comm %d\n", comm_);
                                    ^
[ 84%] Building CXX object src/CMakeFiles/Dsp.dir/Solver/DualDecomp/DdMWAsync.cpp.o
[ 85%] Building CXX object src/CMakeFiles/Dsp.dir/Solver/DualDecomp/DdMWPara.cpp.o
/tmp/DSP/src/Solver/DualDecomp/DdMWPara.cpp: In member function ‘DSP_RTN_CODE DdMWPara::createGroups()’:
/tmp/DSP/src/Solver/DualDecomp/DdMWPara.cpp:150:80: error: ‘MPI_Comm_create_group’ was not declared in this scope
   MPI_Comm_create_group(comm_, subcomm_group_, DSP_MPI_TAG_GROUP_SUB, &subcomm_);
                                                                                ^
/tmp/DSP/src/Solver/DualDecomp/DdMWPara.cpp:193:87: error: ‘MPI_Comm_create_group’ was not declared in this scope
   ierr = MPI_Comm_create_group(comm_, subcomm_group_, DSP_MPI_TAG_GROUP_SUB, &subcomm_);
                                                                                       ^
make[2]: *** [src/CMakeFiles/Dsp.dir/Solver/DualDecomp/DdMWPara.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/Dsp.dir/all] Error 2
make: *** [all] Error 2

**Comment by kibaekkim** [comment]
It looks like your MPI standard version is < 3. The function ``MPI_Comm_create_group`` is available in MPI-3. Please try it with MPI-3.

**Comment by bbrunaud** [comment]
Thanks. I will try it. I got mipch from the Ubuntu 14.04 repos. BTW. Great
work! A lot of progress since I last saw DSP at the AICHE last year.

Regards

Braulio

**Comment by bbrunaud** [comment]
What's the name of the library that's being used?. I tried removing openmpi and keeping only mpich. The mpiexec in my system is mpiexec.hydra and its version is 3.0.4. I still get the same problem when trying to compile

**Comment by bbrunaud** [comment]
I solve the problem by uninstalling openmpi. I had openmpi 1.6 and mpich 3.0.4. cmake was catching the first one.
