### ISSUE TITLE
Failed to solve SMPS test problems

### ISSUE THREAD

**Issue by juantorres91** [Argonne-National-Laboratory/DSP#11]
Hi Victor and Kibbaek,

I'm having problems trying to solve SMPS test problems in serial and parallel (sslp and dcap libraries) using the default solver settings (:Dual), most of the time I'm getting the following output:

![image](https://cloud.githubusercontent.com/assets/20445793/25193060/43e802c8-24fb-11e7-81a1-c3a65914e86c.png)

After many iterations the duality gap is constant. Futhermore, it also failed to solve the farmer test problem:

![image](https://cloud.githubusercontent.com/assets/20445793/25193116/8df54678-24fb-11e7-96ab-dcd856e600d7.png)

Sincerely, 

Juan

**Comment by kibaekkim** [comment]
Sorry for the delay. I have found and fixed the bug in calculating upper bounds. The Julia syntax has been also fixed.

**Comment by juantorres91** [comment]
Hi Kibbaek,


Thanks for all you help, everything is working now. I have a final question for you, is it posible to use cplex or gurobi as instance solver?


Sincerely,


Juan José Torres Figueroa

Asistente Graduado

Departamento de Ingeniería Química

Universidad de los Andes

Bogotá, Colombia

+57 3394949 Ext.1776

________________________________
De: Kibaek Kim <notifications@github.com>
Enviado: lunes, 01 de mayo de 2017 4:47:30 p. m.
Para: Argonne-National-Laboratory/DSP
Cc: Juan Jose Torres Figueroa; Author
Asunto: Re: [Argonne-National-Laboratory/DSP] Failed to solve SMPS test problems (#11)


Sorry for the delay. I have found and fixed the bug in calculating upper bounds. The Julia syntax has been also fixed.
