### ISSUE TITLE
Dual decomposition failed when scenarios are fewer than the first-stage variables

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#129]
Solving the `farmers` problem with only the first two scenarios or with only one scenario through subgradient dual decomposition in the `master` branch will give the segmentation fault. This was brought to my attention when I was testing my code in `dev/miqp` branch. Things works fine when the number of scenario is greater than the number of the first stage variable.

This may be because of the function in DecTssModel.cpp `evalLhsCouplingRowAlternative`. One of the input parameters is incorrect.

**Comment by kibaekkim** [comment]
@cheesecakeball Did that happen when using subgradient method? I cannot reproduce with
```
./bin/runDsp --algo dd --smps ../examples/smps/farmer2
```
where `farmer2` is the two-scenario instance with `farmer2.sto` as follows:
```
*23456789 123456789 123456789 123456789 123456789 123456789
STOCH         FARMER
SCENARIOS
 SC SCEN01    ROOT            0.5   PERIOD2          
    x0        cons1           3                    
    x1        cons2           3.6                   
    x2        cons3          -24 
 SC SCEN02    ROOT            0.5   PERIOD2          
    x0        cons1           2.5                    
    x1        cons2           3                   
    x2        cons3          -20   
ENDATA
```

**Comment by cheesecakeball** [comment]
> @cheesecakeball Did that happen when using subgradient method? I cannot reproduce the bug with
> 
> ```
> ./bin/runDsp --algo dd --smps ../examples/smps/farmer2
> ```
> 
> where `farmer2` is the two-scenario instance with `farmer2.sto` as follows:
> 
> ```
> *23456789 123456789 123456789 123456789 123456789 123456789
> STOCH         FARMER
> SCENARIOS
>  SC SCEN01    ROOT            0.5   PERIOD2          
>     x0        cons1           3                    
>     x1        cons2           3.6                   
>     x2        cons3          -24 
>  SC SCEN02    ROOT            0.5   PERIOD2          
>     x0        cons1           2.5                    
>     x1        cons2           3                   
>     x2        cons3          -20   
> ENDATA
> ```

Yes, this happens when using subgradient method. Is the example you are running using the subgradient method?

**Comment by cheesecakeball** [comment]
fixed through https://github.com/Argonne-National-Laboratory/DSP/commit/18106ef629c052db18a1a99cb0f5c537e98d38b3 in `dev/miqp` branch
