### ISSUE TITLE
Dual Decomposition Retrieve Wrong Parameter When adding Benders Cuts

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#130]
https://github.com/Argonne-National-Laboratory/DSP/blob/3c718fdb6675ab7c34ba645ecfe43dd4558a6ba1/src/Solver/DualDecomp/DdMWSerial.cpp#L66

Should it be `DD/SUB/SOLVER`?

**Comment by kibaekkim** [comment]
You must be right!
