### ISSUE TITLE
How to set optimality gap tolerance

### ISSUE THREAD

**Issue by karan-an-1996** [Argonne-National-Laboratory/DSP#135]
Hello everyone,

I am currently struggling with difficulties in finding the parameters for setting optimality gap tolerances for the solving process. Specifically, I am not able to find the parameter responsible for terminating the solving process when a specific optimality gap tolerance of f.e. 5% is reached for the DE algorithm as well as the parameter responsible for terminating the solving process when a optimality gap tolerance of 5% is reached for the subproblems of the DD algorithm. 

Thanks in advance!
Karan

**Comment by kibaekkim** [comment]
I have added the parameters in #136. Once passing the automatic test, it will be merged to `master`.

By the way, setting the optimality gap to the DD subproblems may not be tested with extensive numerical test instances.

**Comment by karan-an-1996** [comment]
Thanks a lot!

Do I need to pull the master again then and reinstall the solver?

**Comment by kibaekkim** [comment]
Yes, you need to pull the master again. Re-compiling should not take long.
