### ISSUE TITLE
Merge for QCQP

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/DSP#142]
I have changed the PRs #139 #140 being merged to branch `dev/qcqp`, where we need to take care of any conflicts before merging them to `master`.

@gbyeon, @cheesecakeball : Can you please summarize your implementations under this issue so that you two are on the same page?

**Comment by cheesecakeball** [comment]
1. Implement the data structure of quadratic objectives in the first stage and second stage problem. The data structure is using CoinPackedMatrix.
2. dsp can solve deterministic equivalent of miqp with quadratic objectives in the first stage and second stage (by loadquadraticobjective() function)

**Comment by gbyeon** [comment]
1. Defined a quadratic constraint data file format which has an extension of '.txt'. It extends the smps file and uses the variable names given in smps file.  
2. Created a new model class 'DecTssQcModel' which inherits from the 'DecTssModel'
- The 'DecTssQcModel' class can read from the quadratic constraint data file. 
- The 'DecTssQcModel' also has 'loadQuadraticRows' function that can receive the qc information directly from the code. This function can be used to interface with DSPopt.jl
- 'DecTssQcModel' has a vector of 'QcRowDataScen', each element of which is a data structure for each scenario that carries all the qc information required to add quadratic constraints to each subproblem (currently, the structure includes data that is required by 'Cplex')
3. Added a pure virtual member 'isQuadratic()' to 'DecModel.h'. The 'DecBlkModel' and 'DecTssModel' return false for this member, while 'DecTssQcModel' returns true. This can be used to decide whether it is necessary to downcast the current 'DecModel' to 'DecTssQcModel' and retrieve and use the qc related information and functions or not.
4. Added 'DspOsi.h' members 'ismip_', 'isqp_', 'isqcp_' that can be used to determine which solve method to use. Detailed usage of them can be found in 'DspOsiCpx.h'

**Comment by gbyeon** [comment]
- Current version can solve quadratically constrained models with 'Deterministic equivalence (de)' and 'Dual Decomposition (dd)' methods using Cplex.
- Current version supports quadratic constraints that involve only second stage variables.
- The quadratic data file format for the current version is only able to extend to .cor (i.e., mps) file format.

**Comment by kibaekkim** [comment]
Luckily, there are only a few conflicts between two PRs from @gbyeon and @cheesecakeball. They all look easy to be resolved. Among them, one particular thing to resolve carefully is that @gbyeon is using `isQuadratic` for checking the model, whereas @cheesecakeball is using `isQCQP` for that. Either looks ok to me.
