### ISSUE TITLE
Add tests for MIQP

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/DSP#144]
We need to add tests and unit tests for QP implementations.

**Comment by cheesecakeball** [comment]
Should I add tests written in C code (or some other format)?

**Comment by kibaekkim** [comment]
Can you try reading QP instances from MPS? I see that Coin-OR supports the quadratic objective with `QUADOBJ`.

**Comment by cheesecakeball** [comment]
> Can you try reading QP instances from MPS? I see that Coin-OR supports the quadratic objective with `QUADOBJ`.

Just double-check: we do not want to modify `SMI` code directly, right? In order to read smps files with quadratic objectives, I need to add one more function in readsmps function in SMI package.

**Comment by kibaekkim** [comment]
I was not following this issue (https://github.com/coin-or/Smi/issues/4), but it looks like the functions are already there for quadratic objective. 

Quadratic constraints are different, although Gurobi suggests some new cards such as `QCMATRIX`. This is not even implemented in `CoinMpsIO.hpp` and thus would require more work to do.

**Comment by cheesecakeball** [comment]
> I was not following this issue ([coin-or/Smi#4](https://github.com/coin-or/Smi/issues/4)), but it looks like the functions are already there for quadratic objective.
> 
> Quadratic constraints are different, although Gurobi suggests some new cards such as `QCMATRIX`. This is not even implemented in `CoinMpsIO.hpp` and thus would require more work to do.
> 
> Otherwise, we can start with unit test.

Yes, the function is there. I tested the readQuadraticMps() function in `CoinMPSIO.*` before, it worked. But in order to implement in `SMI`, we need to modify the `SMI` package itself. We talked about this before. The followings are my thoughts.

1. Basically it is just adding the `readQuadraticMps()` function after `readMps()`(not replace `readMps()` as answered in the issue (https://github.com/coin-or/Smi/issues/4)), so that `SMI` is able to read `.cor` file with quadratic objectives.
2. After the above modification, we need to modify this function (https://github.com/coin-or/Smi/blob/00ed389bd4e758ccd71096bf860cbd8cbbdb6513/Smi/src/SmiSmpsIO.cpp#L178) to read stochastic quadratic objective data in `.sto` file. 

I think it is not hard to implement it by modifying the code in `SMI `. But in that way, we need to maintain the `SMI` package. Otherwise, we can derive a new class.

**Comment by kibaekkim** [comment]
OK. I reopened #58. This might be a less priority to the other tasks you have.

Can you test QP functionalities in unit test?

**Comment by cheesecakeball** [comment]
> OK. I reopened #58. This might be a less priority to the other tasks you have.
> 
> Can you test QP functionalities in unit test?

Sure. I am working on that.

**Comment by cheesecakeball** [comment]
Added unit test for MIQP

Functions: `loadQuadraticFirstStage()`, `loadQuadraticSecondStage()`, `solveDe()`

Check the following cases:
A. With stochastic technology matrices and recourse matrices:
1. quadratic objectives in the first stage, linear objectives in the second stage
2. quadratic objectives in the first stage, quadratic objectives in the second stage
3. linear objectives in the first stage, quadratic objectives in the second stage

B. With stochastic quadratic objectives:
1. quadratic objectives in the first stage, quadratic objectives in the second stage

**Comment by kibaekkim** [comment]
@cheesecakeball The test did not pass. Please check that.

**Comment by cheesecakeball** [comment]
> @cheesecakeball The test did not pass. Please check that.

This is because Gurobi is not available in CI (similar to issue #145). By the way, how did you solve issue #145? Through this commit (636e796)?

**Comment by kibaekkim** [comment]
If any specific solvers are used, we need to use macro (e.g., `DSP_HAS_GRB`) in order to enable/disable the code lines. Do you have unit test lines independent to solver?

I resolved #145 by this line: https://github.com/Argonne-National-Laboratory/DSP/blob/master/.travis.yml#L65 But, this does not work for gurobi because the license is activate on a dedicated machine.

**Comment by cheesecakeball** [comment]
Thanks for the answer. My unit test lines all depend on Gurobi, because the checking criterion is based on the solution of the sample problem.

**Comment by cheesecakeball** [comment]
The unit test should be independent of the solver, will modify in `dev/qcqp` branch
