### ISSUE TITLE
Unexpected termination of Travis-ci under linux environment

### ISSUE THREAD

**Issue by gbyeon** [Argonne-National-Laboratory/DSP#149]
https://travis-ci.org/github/Argonne-National-Laboratory/DSP/jobs/741224427#L3255

**Comment by kibaekkim** [comment]
https://stackoverflow.com/questions/49628615/understanding-corrupted-size-vs-prev-size-glibc-error

**Comment by kibaekkim** [comment]
@gbyeon You may want to run `valgrind` on a linux machine.

**Comment by gbyeon** [comment]
resolved by d3b7ac2
