### ISSUE TITLE
Implementing QP interfaces

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/DSP#159]
To complete the implementation of `DspOsi` interfaces for QP,  please implement the QP interfaces for `DspOsiCpx` and `DspOsiScip`.

**Comment by cheesecakeball** [comment]
Quote from [SCIP](https://www.scipopt.org/doc/html/FAQ.php#minlptypes):
"Nonlinear objective functions are not supported by SCIP and must be modeled as constraint function."
Shall I reformulate the problem by modeling the quadratic objective function as constraints?

**Comment by kibaekkim** [comment]
Nope. Let's not do that.

**Comment by kibaekkim** [comment]
@cheesecakeball please make sure that all tests pass before pushing commits to this collaborative PR.

**Comment by kibaekkim** [comment]
@cheesecakeball This still needs test scripts. You can do that in two ways:

- Use SMI to read QP instances and run `ctest`
- Implement unit test codes

Please do at least one of them.
