### ISSUE TITLE
Two different functions for the same role

### ISSUE THREAD

**Issue by kibaekkim** [Argonne-National-Laboratory/DSP#161]
Need to choose either `isQuadratic` or `isQCQP`.

**Comment by cheesecakeball** [comment]
I also found `isqp_` and `isqcp_` in `DspOsi`. Shall we also discard `isQuadratic` and use `isqp_` and `isqcp_`defined in `DspOsi` instead?

**Comment by kibaekkim** [comment]
I see that `isQuadratic` function is used and may need kept. 

Instead, I think `isqp_` and `isqcp_` could be set when functions `loadQuadraticObjective` and `addQuadraticRows`, resp., are called. With this way, we may not need function `setPropType` in `DeDriver.cpp`, `DdSub.cpp`, and `DdWorkerUB.cpp`.

**Comment by kibaekkim** [comment]
@cheesecakeball The commit should have addressed the issue. Please check the commit for future implementation.
