### ISSUE TITLE
Need to allow some tolerance for Ps solution?

### ISSUE THREAD

**Issue by gbyeon** [Argonne-National-Laboratory/DSP#174]
https://github.com/Argonne-National-Laboratory/DSP/blob/7b6134d935786afa273bc9a44e6db81cdd719f62/src/Solver/DualDecomp/DdMWSync.cpp#L761

When testing
`add_test(NAME scip_drdd_mpi_sslp_BC COMMAND mpiexec -np 3 $ENV{PWD}/src/runDsp --algo drdd --smps ${CMAKE_SOURCE_DIR}/examples/dro/sslp_5_25_15_BC --param ${CMAKE_SOURCE_DIR}/test/params_scip.txt --test -98.0705)` on my local laptop, the assertion has failed due to a small negative value of `probability = -2e-8`. Would it be okay to add some tolerance to it like this?:
```
assert(probability >= -1e-6);
assert(probability <= 1.0 + 1e-6);
if (probability < 0 && probability >= -1e-6)
	probability = 0;
else if (probability > 1 && probability <= 1 + 1e-6)
	probability = 1;
```

**Comment by kibaekkim** [comment]
Yes, that would work.
