### ISSUE TITLE
libDsp.so file not found

### ISSUE THREAD

**Issue by gavelasq** [Argonne-National-Laboratory/DSP#19]
After I cloned and installed DSP, I tried solving one of the examples using julia package Dsp and I got this error:

ERROR: LoadError: LoadError: error compiling Type: could not load library "libDsp"
libDsp.so: cannot open shared object file: No such file or directory
Stacktrace:
[1] include_from_node1(::String) at ./loading.jl:576
while loading /home/gavelasq/.julia/v0.6/Dsp/src/Dsp.jl, in expression starting on line 23
while loading /home/gavelasq/Documents/structJuMP_example.jl, in expression starting on line 1

Also, I checked the lib folder and the only file there is README.md.

**Comment by kibaekkim** [comment]
Just to check whether you have followed the instruction, did you define the environment variable? After the installation, you should have seen the message "Please add the following line to the .bash_profile or .bashrc in your home directory ..."

**Comment by gavelasq** [comment]
this is my current /etc/environment:

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/gavelasq/Programs/julia-0d7248e2ff/bin:/home/gavelasq/Programs/DSP/lib:/home/gavelasq/Programs/DSP"

**Comment by kibaekkim** [comment]
Please read and follow this: https://github.com/Argonne-National-Laboratory/DSP/blob/master/INSTALL.md#installation

**Comment by gavelasq** [comment]
This is what I did to install DSP:

1. git clone --recursive https://github.com/Argonne-National-Laboratory/DSP.git
2. Since I am using Ubuntu, I ran this in the Terminal:

apt-get -y install build-essential \
  autoconf \
  automake \
  libmpich-dev \
  cmake \
  libblas-dev \
  liblapack-dev \
  subversion \
  libbz2-dev \
  zlib1g-dev

**Comment by kibaekkim** [comment]
I believe you need to do the following part.

> A shared object is installed in ./lib directory. Once the installation has been successfully done, you need to set environment variable (DY)LD_LIBRARY_PATH. Please add the following line by replacing <DSP_SRC_PATH> with your DSP source directory in ~/.bash_profile (or ~/.bash_aliases): for Linux,
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<DSP_SRC_PATH>/lib

**Comment by gavelasq** [comment]
I executed the following:

echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/gavelasq/Programs/DSP/lib" >> ~/.profile

then I logged off and logged on and I get the same error. The folder DSP/lib does not contain any files except README.md. Is this OK? If not how do I fix it?

**Comment by kibaekkim** [comment]
Did you successfully compile the codes, as instructed in https://github.com/Argonne-National-Laboratory/DSP/blob/master/INSTALL.md#installation?

**Comment by gavelasq** [comment]
I think so. This is the output I get after I try to reinstall DSP:

gavelasq@gavelasq-VirtualBox:~$ sudo apt-get -y install build-essential \
>   autoconf \
>   automake \
>   libmpich-dev \
>   cmake \
>   libblas-dev \
>   liblapack-dev \
>   subversion \
>   libbz2-dev \
>   zlib1g-dev
[sudo] password for gavelasq: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
build-essential is already the newest version (12.1ubuntu2).
libblas-dev is already the newest version (3.6.0-2ubuntu2).
libbz2-dev is already the newest version (1.0.6-8).
liblapack-dev is already the newest version (3.6.0-2ubuntu2).
libmpich-dev is already the newest version (3.2-6build1).
cmake is already the newest version (3.5.1-1ubuntu3).
subversion is already the newest version (1.9.3-2ubuntu1.1).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 238 not upgraded.

**Comment by kibaekkim** [comment]
I am not sure if we are looking at the same installation page. Your command line is not compiling the codes. Which page are you looking at?

**Comment by gavelasq** [comment]
OK. How do I do make my command line to compile the code? (I only went over the "quick instructions section" for debian based distributions)

**Comment by kibaekkim** [comment]
The only thing you need to do is reading and following the instructions. You really need to **READ** this (https://github.com/Argonne-National-Laboratory/DSP#installation) and this (https://github.com/Argonne-National-Laboratory/DSP#julia-interface). Again, please **READ** and FOLLOW what is written, and let me know if you have questions.

**Comment by gavelasq** [comment]
OK. I really read it. As you can see I am new to Ubuntu. I have some questions:
1. Do I need to install MA27 or just move the unpacked folder to ./extra ? if I need to install it, how do I do that? I did not find any help in their webpage.
2. is ./extra different than ./extras? where do I really need to move ma27-1.0. and scipoptsuite-3.1.1?

thanks.

**Comment by kibaekkim** [comment]
MA27 is optional. But, if you are not using CPLEX, I recommend to use it for better computational performance. I just updated the installation document (https://github.com/Argonne-National-Laboratory/DSP/blob/master/INSTALL.md#installation). Hope this helps.

**Comment by kibaekkim** [comment]
@gavelasq please let me know if you managed to do that. If so, I will close the issue.

**Comment by gavelasq** [comment]
I am having problems installing SCIP so I have not been able to install DSP, but I think you can close this issue. Instructions on how to install DSP are more clearer now. Thanks.
