### ISSUE TITLE
All the test failed

### ISSUE THREAD

**Issue by enri07** [Argonne-National-Laboratory/DSP#202]
Hi,

I am trying to install DSP on my computer. By using the file install.md, I followed all the instructions and I changed the path to the CPLEX library in the file UserConfig.cmake. Then I build a new directory "build" and ran **cmake ..** and all seems to work. But when I try to run **ctest** i recive the following sequence:

The following tests FAILED:
	  1 - cpx_de_farmer (Not Run)
	  2 - cpx_dd_farmer (Not Run)
	  3 - cpx_drdd_drslp (Not Run)
	  4 - cpx_drdd_farmer (Not Run)
	  5 - cpx_drdd_sslp_BB (Not Run)
	  6 - cpx_drdd_sslp_BC (Not Run)
	  7 - cpx_drdd_sslp_CC (Not Run)
	  8 - cpx_dw_farmer (Not Run)
	  9 - cpx_qc_de_farmer (Not Run)
	 10 - cpx_qc_dd_farmer (Not Run)
	 11 - cpx_qc_de_farmer2 (Not Run)
	 12 - cpx_qc_dd_farmer2 (Not Run)
	 13 - cpx_qc_de_farmer3 (Not Run)
	 14 - cpx_qc_dd_farmer3 (Not Run)
	 15 - cpx_dd_mpi_farmer (Failed)
	 16 - cpx_drdd_mpi_drslp (Failed)
	 17 - cpx_drdd_mpi_farmer (Failed)
	 18 - cpx_drdd_mpi_sslp_BB (Failed)
	 19 - cpx_drdd_mpi_sslp_BC (Failed)
	 20 - cpx_drdd_mpi_sslp_CC (Failed)
	 21 - cpx_dw_mpi_farmer (Failed)
Errors while running CTest

Can someone help me?

**Comment by kibaekkim** [comment]
Can you provide more information? What is your environment (e.g., os, compiler, ...)? Can you put here the output from `cmake ..`?

**Comment by enri07** [comment]
Thank you for your help.

I'm working on Ubuntu 20.04.2 and the C compiler used to run the command **cmake ..** is GCC 9.3.0.

Here's the output from **cmake ..**:

--The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 9.3.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- The system information: Linux-5.8.0-59-generic.x86_64
-- Build type: Release
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/libmpich.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/libmpichcxx.so (found version "3.1") 
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/libmpichfort.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found /home/enrico/Scrivania/CPLEX/cplex/lib/x86-64_linux/static_pic/libcplex.a
-- Could not find ma27 (disabled OOQP solver)
-- SCIP is required for Benders decomposition. Benders decomposition is disabled with SCIP library.
-- Code coverage: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/enrico/Scrivania/DSP/build

Instead, when I run **ctest** it seems that the problem is the following line for the first 14 tests:

**Could not find executable /home/enri/Scrivania/DSP/build/src/runDsp**

While all the remaining tests are run but fails.

**Comment by kibaekkim** [comment]
The configuration looks fine. Do you see runDsp in the location? If not, it’s likely that the build failed. Can you also put the output from the build?

Kibaek
________________________________

**Comment by enri07** [comment]
In the following photo you can see what's inside the folder build and in some sub-directories:

![DSPutile](https://user-images.githubusercontent.com/87133105/125078400-a0252c00-e0c2-11eb-9083-62adedd4b0c2.png)

Did you mean this?
Thanks a lot for your help.

**Comment by kibaekkim** [comment]
Right. The build must have failed. Can you remove build directory and rebuild the code from the scratch? And please share the screen output from the build (i.e., make).
________________________________

**Comment by enri07** [comment]
Thank you very much! After I launched the command **make** I noticed that the problem was the wrong path specified for CPLEX_INC_DIR. By modifying it I am now able to execute all the tests correctly and now I have both the directories bin and lib inside build.
