### ISSUE TITLE
could not load library "libDsp" in Julia

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/DSP#21]
Hi I'm new at StructJump and DSP,

I have just instaled the DSP solver in Ubuntu, I'm trying to solve several examples

when I do

using DSP

I get this error

ERROR: LoadError: compiling error Type: could not load library "libDsp"
libDsp.so: Unable to open shared object file: File or directory does not exist
Stacktrace:
 [1] include_from_node1 (:: String) at ./loading.jl:576
 [2] eval (:: Module, :: Any) at ./boot.jl:235
 [3] _require (:: Symbol) at ./loading.jl:490
 [4] require (:: Symbol) at ./loading.jl:405
while loading /home/esnil/.julia/v0.6/Dsp/src/Dsp.jl, in expression starting on line 23

I also made environment variable set (DY) LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$Home/esnil/DSP/lib

I was seeing some of the cases already closed in relation to the MPI vesion using. I show these in the list but I do not know which of them to erase or uninstall

rm: can not delete 'libmpichcxx.so.12': Permission denied
rm: can not delete 'libmpichfort.so.12': Permission denied
rm: can not delete 'libmpich.so.12': Permission denied
rm: can not delete 'libmpicxx.so': Permission denied
rm: can not delete 'libmpif77.so': Permission denied
rm: can not delete 'libmpif90.so': Permission denied
rm: can not delete 'libmpifort.so': Permission denied
rm: can not delete 'libmpi.so': Permission denied
rm: can not delete 'libmpi ++. so': Permission denied

Thank you

**Comment by kibaekkim** [comment]
First of all, your ``export`` removes all the other paths. I recommend the following. 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/esnil/DSP/lib
```
with **$HOME**, not **$Home**. Of course, please make sure that you see ``libDsp.so`` in ``$HOME/esnil/DSP/lib``. If you compile DSP in ``$HOME/esnil/DSP/build`` directory, the path must be ``$HOME/esnil/DSP/build/lib``.

I don't know where you get ``StructJuMP`` that is not currently supported for some reasons. Please make sure that you are using ``Dsp.jl`` from https://github.com/kibaekkim/Dsp.jl#intallation.

**Comment by Esnilg** [comment]
![captura de pantalla de 2017-12-15 15-08-52](https://user-images.githubusercontent.com/32929965/34054513-1f00e95e-e1aa-11e7-8440-0f9ea3782e9d.png)

**Comment by Esnilg** [comment]
Hi,

I already found the problem, I did this

unset LD_LIBRARY_PATH

then

export LD_LIBRARY_PATH = $ LD_LIBRARY_PATH: $HOME/DSP/build/lib

and I was able to use Dsp

Thank you very much
