### ISSUE TITLE
bd gives error for solving subproblems with Scip and cplex

### ISSUE THREAD

**Issue by gbyeon** [Argonne-National-Laboratory/DSP#216]
- branch: dev/qcqp-gbyeon
- SCIP version: 8.0.0
- CPLEX version: 20.1

By default, benders subproblem is solved by CLP, which is a linear programming solver. To solve quadratically constrained subproblem, we need to use other solvers supporting quadratic constraints.

To do that, I've manually changed Line 164 `BdSub.cpp` from
`cglp_[i] = createDspOsi(par_->getIntParam("BD/SUB/SOLVER"));`
to
`cglp_[i] = createDspOsi(OsiScip);`

Then, it terminates with segmentation error both for milp and miqcp. The commands tested:
For milp:
`./src/runDsp --algo bd --smps ../examples/smps/farmer --param ../test/params_scip.txt`
For miqcp: for i=1,2,..,5
`./src/runDsp --algo bd --smps ../examples/smps/farmer --quad ../examples/quad/farmer$i --param ../test/params_scip.txt`

**Comment by kibaekkim** [comment]
This may be related to the newer version of SCIP. 
- `master` branch: I could compile the code with SCIP version 7.0.3 and run the MILP example above. 
- `dev/qcqp-gbyeon` branch: I could not compile the code with SCIP version 7.0.3 because some function names in SCIP are different from the implementation in the branch. So, I think the implementation is compatible to SCIP version 8.0.0 only. This is probably why the MILP example is not running.

**Comment by gbyeon** [comment]
- Yes, there had been a change in functions for dealing with quadratic constraints in SCIP version 8.0.0, so I changed it for it to be compatible with the recent version. Should we have the DSP use different functions depending on the SCIP version?

- Sorry, there is one missing parameter in the params_scip.txt. The error occurs if I let the `BD/SUB/SOLVER` use `OsiScip` instead of `OsiClp`, which is not suitable for solving nonlinear subproblems.

**Comment by kibaekkim** [comment]
> Should we have the DSP use different functions depending on the SCIP version?

No, we can just enforce to use the version 8.

**Comment by kibaekkim** [comment]
```
./bin/runDsp --algo bd --smps ../examples/smps/farmer --quad ../examples/quad/farmer4 --param ../test/params_scip.txt
```



  | CPLEX | SCIP
-- | -- | --
DE | 41385.4, 41385.4 | 41348.7, 41348.7
DD | 41348.8, 41370.6 | 41348.8, 41348.7
DW | not supported |  not supported
BD | 39090.9, 39090.9 | segfault

```
Not supported. in OsiScipSolverInterface::setWarmStart
Not supported. in OsiScipSolverInterface::getWarmStart
Not supported. in OsiScipSolverInterface::setWarmStart
[cons_linear.c:15903] ERROR: Error <-9> in function call
[cons.c:6434] ERROR: Error <-9> in function call
[prob.c:584] ERROR: Error <-9> in function call
[scip_solve.c:410] ERROR: Error <-9> in function call
WARNING: Transformed variable <t_var2> not released when freeing SCIP problem <t_Dsp>.
WARNING: Transformed variable <t_var0> not released when freeing SCIP problem <t_Dsp>.
[scip_solve.c:2707] ERROR: Error <-9> in function call
[OsiScipSolverInterface.cpp:28] ERROR: Error <-9> in function call
Not supported. in OsiScipSolverInterface::getWarmStart
[Kibaeks-MacBook-Pro:89470] *** Process received signal ***
[Kibaeks-MacBook-Pro:89470] Signal: Segmentation fault: 11 (11)
[Kibaeks-MacBook-Pro:89470] Signal code: Address not mapped (1)
[Kibaeks-MacBook-Pro:89470] Failing at address: 0x20
[Kibaeks-MacBook-Pro:89470] *** End of error message ***
[1]    89470 segmentation fault  ./bin/runDsp --algo bd --smps ../examples/smps/farmer --quad  --param
```

**Comment by kibaekkim** [comment]
We decided to disable the Benders algorithm for MIQCP until any further decision.
