### ISSUE TITLE
SimpleVector.C:(.text+0xbc4): referencia a `daxpy_' sin definir

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/DSP#25]
Hi,

model name      : Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
stepping        : 4
microcode       : 0x42c
cpu MHz         : 1253.515
cache size      : 20480 KB
physical id     : 0
siblings        : 16
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes

I have this problem before make

[esnil@localhost build]$ cmake ..
-- The system information: Linux-3.10.0-693.21.1.el7.x86_64.x86_64
-- A library with BLAS API found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Configuring done
WARNING: Target "Dsp" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Dsp" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "runDsp" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "runDsp" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/esnil/DSP/build
[esnil@localhost build]$ make
[  8%] Built target CoinUtils
[ 16%] Built target Osi
[ 25%] Built target Clp
[ 33%] Built target OOQP
[ 41%] Built target Smi
[ 94%] Built target DspCore
Linking CXX shared library libDsp.so
../lib/libCoinUtils.a(CoinFactorization2.o): En la función `CoinFactorization::factorDense()':
CoinFactorization2.cpp:(.text+0x465): referencia a `dgetrf_' sin definir
../lib/libCoinUtils.a(CoinFactorization3.o): En la función `CoinFactorization::updateColumnL(CoinIndexedVector*, int*) const':
CoinFactorization3.cpp:(.text+0xe1a): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinFactorization4.o): En la función `CoinFactorization::updateColumnTransposeL(CoinIndexedVector*) const':
CoinFactorization4.cpp:(.text+0x2efa): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::updateColumn(CoinIndexedVector*, CoinIndexedVector*, bool) const':
CoinDenseFactorization.cpp:(.text+0x799): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::updateTwoColumnsFT(CoinIndexedVector*, CoinIndexedVector*, CoinIndexedVector*, bool)':
CoinDenseFactorization.cpp:(.text+0xe30): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::updateColumnTranspose(CoinIndexedVector*, CoinIndexedVector*) const':
CoinDenseFactorization.cpp:(.text+0x1841): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::factor()':
CoinDenseFactorization.cpp:(.text+0x1f8c): referencia a `dgetrf_' sin definir
../lib/libooqpdense.a(DenseSymMatrix.o): En la función `DenseSymMatrix::mult(double, double*, int, double, double*, int)':
DenseSymMatrix.C:(.text+0x6d1): referencia a `dsymv_' sin definir
../lib/libooqpdense.a(DenseSymMatrix.o): En la función `DenseSymMatrix::mult(double, OoqpVector&, double, OoqpVector&)':
DenseSymMatrix.C:(.text+0x7ad): referencia a `dsymv_' sin definir
../lib/libooqpdense.a(DeSymIndefSolver.o): En la función `DeSymIndefSolver::matrixChanged()':
DeSymIndefSolver.C:(.text+0x261): referencia a `dsytrf_' sin definir
../lib/libooqpdense.a(DeSymIndefSolver.o): En la función `DeSymIndefSolver::solve(OoqpVector&)':
DeSymIndefSolver.C:(.text+0x331): referencia a `dsytrs_' sin definir
../lib/libooqpdense.a(DenseGenMatrix.o): En la función `DenseGenMatrix::mult(double, double*, int, double, double*, int)':
DenseGenMatrix.C:(.text+0x798): referencia a `dgemv_' sin definir
../lib/libooqpdense.a(DenseGenMatrix.o): En la función `DenseGenMatrix::mult(double, OoqpVector&, double, OoqpVector&)':
DenseGenMatrix.C:(.text+0x8ea): referencia a `dgemv_' sin definir
../lib/libooqpdense.a(DenseGenMatrix.o): En la función `DenseGenMatrix::transMult(double, double*, int, double, double*, int)':
DenseGenMatrix.C:(.text+0x9de): referencia a `dgemv_' sin definir
../lib/libooqpdense.a(DenseGenMatrix.o): En la función `DenseGenMatrix::transMult(double, OoqpVector&, double, OoqpVector&)':
DenseGenMatrix.C:(.text+0xb30): referencia a `dgemv_' sin definir
../lib/libooqpdense.a(DenseStorage.o): En la función `DenseStorage::atAddOuterProductOf(int, int, double, double*, int, int)':
DenseStorage.C:(.text+0xe38): referencia a `dsyr_' sin definir
../lib/libooqpdense.a(DenseStorage.o): En la función `DenseStorage::addToDiagonalAt(double, double*, int, int, int)':
DenseStorage.C:(.text+0xf4f): referencia a `daxpy_' sin definir
../lib/libooqpbase.a(SimpleVector.o): En la función `SimpleVector::scale(double)':
SimpleVector.C:(.text+0xb0e): referencia a `dscal_' sin definir
../lib/libooqpbase.a(SimpleVector.o): En la función `SimpleVector::axpy(double, OoqpVector&)':
SimpleVector.C:(.text+0xbc4): referencia a `daxpy_' sin definir
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [src/libDsp.so] Error 1
make[1]: *** [src/CMakeFiles/Dsp.dir/all] Error 2
make: *** [all] Error 2

Can you help me?
thanks

**Comment by kibaekkim** [comment]
It looks like that CMake could not find some libraries (probably BLAS or LAPACK). You may want to check if your CMake or compiler can link to those libraries.

**Comment by Esnilg** [comment]
Hi, 

I already have the packages installed

[esnil@localhost build]$ sudo yum -y install cmake blas lapack subversion make autoconf automake bzip2 zlib
Complementos cargados:fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.orbyta.com
 * epel: epel.gtdinternet.com
 * extras: mirror.orbyta.com
 * updates: mirror.orbyta.com
El paquete cmake-2.8.12.2-2.el7.x86_64 ya se encuentra instalado con su versión más reciente
El paquete blas-3.4.2-8.el7.x86_64 ya se encuentra instalado con su versión más reciente
El paquete lapack-3.4.2-8.el7.x86_64 ya se encuentra instalado con su versión más reciente
El paquete subversion-1.7.14-11.el7_4.x86_64 ya se encuentra instalado con su versión más reciente
El paquete 1:make-3.82-23.el7.x86_64 ya se encuentra instalado con su versión más reciente
El paquete autoconf-2.69-11.el7.noarch ya se encuentra instalado con su versión más reciente
El paquete automake-1.13.4-3.el7.noarch ya se encuentra instalado con su versión más reciente
El paquete bzip2-1.0.6-13.el7.x86_64 ya se encuentra instalado con su versión más reciente
El paquete zlib-1.2.7-17.el7.x86_64 ya se encuentra instalado con su versión más reciente
Nada para hacer

when I run cmake .. , I get this

[esnil@localhost build]$ cmake ..
-- The system information: Linux-3.10.0-693.21.1.el7.x86_64.x86_64
CMake Error at /usr/share/cmake/Modules/FindBLAS.cmake:594 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/esnil/DSP/build/CMakeFiles/CMakeOutput.log".
See also "/home/esnil/DSP/build/CMakeFiles/CMakeError.log".

then I try to run it with the command: 
I get this
[esnil@localhost build]$ cmake .. -DBLAS_LIBRARIES=/usr/local/lib/ -DLAPACK_LIBRARIES=/usr/local/lib/
-- The system information: Linux-3.10.0-693.21.1.el7.x86_64.x86_64
-- A library with BLAS API found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
CMake Warning at extra/CMakeLists.txt:24 (message):
  Library ma27 cannot be found.


CMake Warning at extra/CMakeLists.txt:25 (message):
  OOQP is disabled.


-- Configuring done
WARNING: Target "Dsp" requests linking to directory "/usr/local/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "runDsp" requests linking to directory "/usr/local/lib/".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/esnil/DSP/build

finally make
...
[ 94%] Built target DspCore
Linking CXX shared library libDsp.so
../lib/libCoinUtils.a(CoinFactorization2.o): En la función `CoinFactorization::factorDense()':
CoinFactorization2.cpp:(.text+0x465): referencia a `dgetrf_' sin definir
../lib/libCoinUtils.a(CoinFactorization3.o): En la función `CoinFactorization::updateColumnL(CoinIndexedVector*, int*) const':
CoinFactorization3.cpp:(.text+0xe1a): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinFactorization4.o): En la función `CoinFactorization::updateColumnTransposeL(CoinIndexedVector*) const':
CoinFactorization4.cpp:(.text+0x2efa): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::updateColumn(CoinIndexedVector*, CoinIndexedVector*, bool) const':
CoinDenseFactorization.cpp:(.text+0x799): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::updateTwoColumnsFT(CoinIndexedVector*, CoinIndexedVector*, CoinIndexedVector*, bool)':
CoinDenseFactorization.cpp:(.text+0xe30): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::updateColumnTranspose(CoinIndexedVector*, CoinIndexedVector*) const':
CoinDenseFactorization.cpp:(.text+0x1841): referencia a `dgetrs_' sin definir
../lib/libCoinUtils.a(CoinDenseFactorization.o): En la función `CoinDenseFactorization::factor()':
CoinDenseFactorization.cpp:(.text+0x1f8c): referencia a `dgetrf_' sin definir
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [src/libDsp.so] Error 1
make[1]: *** [src/CMakeFiles/Dsp.dir/all] Error 2
make: *** [all] Error 2

**Comment by kibaekkim** [comment]
This is the same issue as in #26. Please see the comment there.
