### ISSUE TITLE
Negative step size in subgradient method

### ISSUE THREAD

**Issue by hideakiv** [Argonne-National-Laboratory/DSP#254]
When solving `examples/smps/sslp_5_25_50` with `--algo dd` and parameter set to `int DD/MASTER_ALGO 4`, DSP does not converge:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/18362351/218198958-d6cb71dc-c17a-4ffd-b49d-7ad3f997053a.png">
Some step sizes are negative: `debug: -> step size -9.430063e+01`
The optimal objective of this problem is -121.6

**Comment by kibaekkim** [comment]
@hideakiv Negative step size must be a bug. But even after fixing it, I don't expect that the subgradient method would terminate at any convergence for this non-soomth problem.

**Comment by hideakiv** [comment]
There is an issue here where the objective coefficients of the recourse problem not getting rescaled by the probability: https://github.com/Argonne-National-Laboratory/DSP/blob/release/src/Solver/DualDecomp/DdWorkerUB.cpp#L134

**Comment by hideakiv** [comment]
adressed in #257.
