### ISSUE TITLE
A required library with BLAS API not found

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/DSP#26]
Dear,

Again try to install everything step by step and this is the problem I presented:

[esnil@localhost DSP]$ mkdir build
[esnil@localhost DSP]$ cd build/
[esnil@localhost build]$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The system information: Linux-3.10.0-693.21.1.el7.x86_64.x86_64
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake/Modules/FindBLAS.cmake:594 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/esnil/DSP/build/CMakeFiles/CMakeOutput.log".
See also "/home/esnil/DSP/build/CMakeFiles/CMakeError.log".

What I can do?
 The lib are in:

[esnil@localhost build]$ ls -l /usr/lib64/liblapack*
lrwxrwxrwx. 1 root root      19 mar 23 13:42 /usr/lib64/liblapacke.so -> liblapacke.so.3.4.2
lrwxrwxrwx. 1 root root      19 mar 21 11:58 /usr/lib64/liblapacke.so.3 -> liblapacke.so.3.4.2
lrwxrwxrwx. 1 root root      19 mar 21 11:58 /usr/lib64/liblapacke.so.3.4 -> liblapacke.so.3.4.2
-rwxr-xr-x. 1 root root 1965960 ago  2  2017 /usr/lib64/liblapacke.so.3.4.2
lrwxrwxrwx. 1 root root      18 mar 23 13:42 /usr/lib64/liblapack.so -> liblapack.so.3.4.2
lrwxrwxrwx. 1 root root      18 mar 21 11:58 /usr/lib64/liblapack.so.3 -> liblapack.so.3.4.2
lrwxrwxrwx. 1 root root      18 mar 21 11:58 /usr/lib64/liblapack.so.3.4 -> liblapack.so.3.4.2
-rwxr-xr-x. 1 root root 5638352 ago  2  2017 /usr/lib64/liblapack.so.3.4.2
[esnil@localhost build]$ ls -l /usr/lib64/libblas*
lrwxrwxrwx. 1 root root     16 mar 23 13:42 /usr/lib64/libblas.so -> libblas.so.3.4.2
lrwxrwxrwx. 1 root root     16 mar 21 11:58 /usr/lib64/libblas.so.3 -> libblas.so.3.4.2
lrwxrwxrwx. 1 root root     16 mar 21 11:58 /usr/lib64/libblas.so.3.4 -> libblas.so.3.4.2
-rwxr-xr-x. 1 root root 364800 ago  2  2017 /usr/lib64/libblas.so.3.4.2

[esnil@localhost build]$ ls -l /usr/local/lib/libblas*
-rw-r--r--. 1 root root 805542 mar 21 15:49 /usr/local/lib/libblas.a
[esnil@localhost build]$ ls -l /usr/local/lib/liblapack*
-rw-r--r--. 1 root root 12372712 mar 21 15:51 /usr/local/lib/liblapack.a

file CMakeError.log

Determining if the function sgemm_ exists failed with the following output:
Change Dir: /home/esnil/DSP/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec3121734220/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3121734220.dir/build.make CMakeFiles/cmTryCompileExec3121734220.dir/build
gmake[1]: se ingresa al directorio `/home/esnil/DSP/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/esnil/DSP/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3121734220.dir/CheckFunctionExists.c.o
/usr/bin/gcc   -DCHECK_FUNCTION_EXISTS=sgemm_   -o CMakeFiles/cmTryCompileExec3121734220.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec3121734220
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3121734220.dir/link.txt --verbose=1
/usr/bin/gcc   -DCHECK_FUNCTION_EXISTS=sgemm_    CMakeFiles/cmTryCompileExec3121734220.dir/CheckFunctionExists.c.o  -o cmTryCompileExec3121734220 -rdynamic /usr/local/lib/libblas.a 
/usr/local/lib/libblas.a(xerbla.f.o): En la función `xerbla_':
xerbla.f:(.text+0x79): referencia a `_gfortran_st_write' sin definir
xerbla.f:(.text+0x90): referencia a `_gfortran_string_len_trim' sin definir
xerbla.f:(.text+0xb3): referencia a `_gfortran_transfer_character_write' sin definir
xerbla.f:(.text+0xd1): referencia a `_gfortran_transfer_integer_write' sin definir
xerbla.f:(.text+0xe0): referencia a `_gfortran_st_write_done' sin definir
xerbla.f:(.text+0xef): referencia a `_gfortran_stop_string' sin definir
collect2: error: ld devolvió el estado de salida 1
gmake[1]: *** [cmTryCompileExec3121734220] Error 1
gmake[1]: se sale del directorio `/home/esnil/DSP/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTryCompileExec3121734220/fast] Error 2

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/esnil/DSP/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec4280868081/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec4280868081.dir/build.make CMakeFiles/cmTryCompileExec4280868081.dir/build
gmake[1]: se ingresa al directorio `/home/esnil/DSP/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/esnil/DSP/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec4280868081.dir/CheckSymbolExists.c.o
/usr/bin/gcc    -o CMakeFiles/cmTryCompileExec4280868081.dir/CheckSymbolExists.c.o   -c /home/esnil/DSP/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec4280868081
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec4280868081.dir/link.txt --verbose=1
/usr/bin/gcc       CMakeFiles/cmTryCompileExec4280868081.dir/CheckSymbolExists.c.o  -o cmTryCompileExec4280868081 -rdynamic 
CMakeFiles/cmTryCompileExec4280868081.dir/CheckSymbolExists.c.o: En la función `main':
CheckSymbolExists.c:(.text+0x16): referencia a `pthread_create' sin definir
collect2: error: ld devolvió el estado de salida 1
gmake[1]: *** [cmTryCompileExec4280868081] Error 1
gmake[1]: se sale del directorio `/home/esnil/DSP/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTryCompileExec4280868081/fast] Error 2

File /home/esnil/DSP/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/esnil/DSP/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec3343838150/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3343838150.dir/build.make CMakeFiles/cmTryCompileExec3343838150.dir/build
gmake[1]: se ingresa al directorio `/home/esnil/DSP/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/esnil/DSP/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3343838150.dir/CheckFunctionExists.c.o
/usr/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec3343838150.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec3343838150
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3343838150.dir/link.txt --verbose=1
/usr/bin/gcc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec3343838150.dir/CheckFunctionExists.c.o  -o cmTryCompileExec3343838150 -rdynamic -lpthreads 
/usr/bin/ld: no se puede encontrar -lpthreads
collect2: error: ld devolvió el estado de salida 1
gmake[1]: *** [cmTryCompileExec3343838150] Error 1
gmake[1]: se sale del directorio `/home/esnil/DSP/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTryCompileExec3343838150/fast] Error 2

**Comment by kibaekkim** [comment]
This looks something that ``CMake`` cannot detect ``BLAS`` library on your machine. Both ``CMake`` and ``BLAS`` are third-party software packages. I believe that the issue must be hardware dependent. So, unfortunately, I cannot say much about that. 

I would google your issue and find similar cases as yours; or contact ``CMake`` community.

**Comment by Esnilg** [comment]
Hello,
Now fix the problem, update cmake from 2.8.12.2 to 3.6.2

**Comment by kibaekkim** [comment]
@Esnilg Glad to hear that!
