### ISSUE TITLE
Error: Subproblem 0 returns unexpected status 3998

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/DSP#28]
Hi,

I'm running an examples using DSP with descomposition Benders. I would like to know what the following error means

Finding a good lower bound using Dual Decomposition...
OOQP is not available for QP solve.
CPLEX is not available for QP solve.

DUAL DECOMPOSITION ITERATION INFORMATION:
* master   = objective function value of the master problem.
* primobj  = best primal objective function value.
* dualobj  = best dual objective function value.
* a.gap(%) = Approximate gap between master and dualobj.
* d.gap(%) = Duality gap between primobj and dualobj.
* times    = wall clock time in seconds.

  iter         master        primobj        dualobj  a.gap(%)  d.gap(%)    time
 D   0  +6.103975e+04          Large  +1.386196e+04     77.29    100.00    11.1
Warning: subproblem 1 solution status is 3002
     1  -4.038858e+04          Large  +1.386196e+04    134.32    100.00    12.7
     2  -1.025870e+06          Large  +1.386196e+04    101.35    100.00    13.5
     3  -1.028108e+06          Large  +1.386196e+04    101.35    100.00    13.8
     4  -1.028109e+06          Large  +1.386196e+04    101.35    100.00    14.8
     5  -1.028374e+06          Large  +1.386196e+04    101.35    100.00    15.1
     6  -1.028375e+06          Large  +1.386196e+04    101.35    100.00    16.3
     7  -1.033255e+06          Large  +1.386196e+04    101.34    100.00    16.6
     8  -1.034189e+06          Large  +1.386196e+04    101.34    100.00    17.1
     9  -1.034506e+06          Large  +1.386196e+04    101.34    100.00    17.5
The iteration limit is reached.
Best lower bound 1.386196e+04, time elapsed: 17.86 sec.
presolving (4 rounds):
 273 deleted vars, 271 deleted constraints, 0 added constraints, 287 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 1 cliques
presolved problem has 149 variables (70 bin, 67 int, 0 impl, 12 cont) and 9 constraints

Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
Error: Subproblem 0 returns unexpected status 3998
 time | node  | left  |LP iter|LP it/n| mem |mdpt |frac |vars |cons |cols |rows |cuts |confs|strbr|  dualbound   | primalbound  |  gap   
s 1.6s|     1 |     0 |     5 |     - |1152k|   0 |   - | 149 |   9 | 149 |   8 |   2 |   0 |   0 | 1.386196e+04 | 1.386196e+04 |   0.00%
  1.6s|     1 |     0 |     5 |     - |1152k|   0 |   - | 149 |   9 | 149 |   8 |   2 |   0 |   0 | 1.386196e+04 | 1.386196e+04 |   0.00%

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 1.56
Solving Nodes      : 1
Primal Bound       : +1.38619560931190e+04 (1 solutions)
Dual Bound         : +1.38619560931190e+04
Gap                : 0.00 %
Error: Subproblem 0 returns unexpected status 3998

13861.95609311904

Thank you

**Comment by kibaekkim** [comment]
My guess is that you are running a serial version, where some of the subproblems are infeasible. In the serial version, when some subproblems were infeasible, the rests are not solved and marked as ``DSP_STAT_NOT_SOLVED`` (which is code ``3998``).  The algorithm should not return the error code in this case. I am fixing and pushing the code. Please pull and compile the code again before you try again.
