### ISSUE TITLE
Questions about DSP and DSPopt

### ISSUE THREAD

**Issue by GBianchiM** [Argonne-National-Laboratory/DSP#280]
Good afternoon, I hope this message finds you well. I am reaching out to ask a few questions about a stochastic mathematical model that I am trying to solve using Benders decomposition with the DSP repository. I have been using this repository through its Julia interface, DSPopt.

1.- My model includes binary variables in the second stage. Is DSP capable of solving decomposition problems with binary variables in the second stage?

2.- I am trying to determine which type of solver DSP uses to solve mathematical models. I would personally like to use Gurobi, but I am unsure how to configure this.

3.- Is there any Runtime advantage between DSP and DSPopt? When I tried solving the "farmer" example, I received different values from each.

4.- Does DSP provide any algorithm to generate the SMPS format for input into DSP? I have been looking for a tool to assist with this due to the complexity of my mathematical model, but I haven't found a suitable solution.

**Comment by kibaekkim** [comment]
> 1.- My model includes binary variables in the second stage. Is DSP capable of solving decomposition problems with binary variables in the second stage?

DSP has multiple decomposition algorithms. If you choose Dantzig-Wolfe decomposition, it can solve the problems with second-stage binary variables. If you choose Dual decomposition, it finds a Lagrangian lower bound and tries to find a good upper bound (i.e., good feasible solutions). This performs pretty well in many problems, meaning the gap between lower and upper bounds could be very small (e.g., 1% or less). If you choose Benders, DSP automatically relaxes the second-stage integer variables to continuous variables.

> 2.- I am trying to determine which type of solver DSP uses to solve mathematical models. I would personally like to use Gurobi, but I am unsure how to configure this.

You need to set up the environment variables `GUROBI_LIB_DIR` and `GUROBI_INC_DIR`, pointing to the directories containing library and header files, respectively.

https://github.com/Argonne-National-Laboratory/DSP/blob/8ceedb43bd7c81aeecfe2ad26030d630ab458261/UserConfig.cmake#L5-L6

> 3.- Is there any Runtime advantage between DSP and DSPopt? When I tried solving the "farmer" example, I received different values from each.

If you get different solution times, yes it is expected. `DSPopt` is a modeling interface that internally uses `DSP`. If you get different solution values, I suspect the default parameter values may be set differently.

> 4.- Does DSP provide any algorithm to generate the SMPS format for input into DSP? I have been looking for a tool to assist with this due to the complexity of my mathematical model, but I haven't found a suitable solution.

Great question! With a grad student as a summer internship project, I started the project to implement SMPS reader/writer and collect some instances. It has been in my private repo. I just made it public: https://github.com/kibaekkim/SIPLIB.jl

**Comment by GBianchiM** [comment]
Thank you for your quick response. I really appreciate your help.

I have two additional questions:

You mentioned that the Benders decomposition relaxes the integer variables. My question is: when the algorithm finishes, are the relaxed variables converted back into integer variables, in this case binary variables?

I used the Dantzig-Wolfe method to solve my model, but its performance is worse than my implementation of the model in its extensive form, solved with the Gurobi optimizer. I am not sure if this performance is due to a mistake in my implementation or some other reason. Do you have any insights or suggestions on this issue?

Thank you in advance for your guidance.

**Comment by kibaekkim** [comment]
> when the algorithm finishes, are the relaxed variables converted back into integer variables, in this case binary variables?

Note that only the second-stage integer variables are relaxed. The algorithm still finds a first-stage feasible solution, which is feasible under the complete recourse assumption. With the first-stage solution obtained from the algorithm, you can compute the objective value (primal bound) by evaluating the second-stage recourse function.

> I used the Dantzig-Wolfe method to solve my model, but its performance is worse than my implementation of the model in its extensive form, solved with the Gurobi optimizer. I am not sure if this performance is due to a mistake in my implementation or some other reason. Do you have any insights or suggestions on this issue?

Such performance is expected for small instances. This is not specific for Dantzig-Wolfe but for most decomposition methods, which would outperform non-decomposition algorithms for large-scale problem instances. If you can generate the problem instances with increasing size, you may find that the decomposition method starts outperforming after a certain size.

**Comment by GBianchiM** [comment]
Thank you for your response; it is very useful for my experiments. I have some additional questions:

1.- How can I set a time limit and a minimum GAP in the DSP algorithms?

2.- In Benders decomposition, the second stage is relaxed. However, in this stage, should the variables be converted into binary variables to properly evaluate the objective function? I have decomposed a mathematical model for the VRPTW, but I am unsure whether relaxing the binary variables (routing variables) in the second stage will result in a logical solution.

**Comment by kibaekkim** [comment]
> How can I set a time limit and a minimum GAP in the DSP algorithms?

You can use the parameter file if you are directly using binary file in terminal: https://dsp.readthedocs.io/en/stable/parameters/ An example is available at: `test/params_grb.txt`

> In Benders decomposition, the second stage is relaxed. However, in this stage, should the variables be converted into binary variables to properly evaluate the objective function?

Yes

> I have decomposed a mathematical model for the VRPTW, but I am unsure whether relaxing the binary variables (routing variables) in the second stage will result in a logical solution.

I suggest to use Dual Decomposition first, which would give you valid upper and lower bounds (i.e., primal and dual bounds). This method often finds very good solutions with small gap. Then, you can try Benders. If you have binary variables in the second stage, the final objective value is likely to be smaller (in minimization sense; thus worse) than the dual bound obtained from Dual Decomposition.

**Comment by GBianchiM** [comment]
Thank you very much for your response.

**Comment by kibaekkim** [comment]
I am closing this issue. But feel free to reopen it or create new.
