### ISSUE TITLE
Problem to get the variables of the first stage

### ISSUE THREAD

**Issue by Esnilg** [Argonne-National-Laboratory/DSP#29]
Dear,

I have a problem with the first stage solution, 
when I solve the problem in an extended way I get a solution that is different when using the bender decomposition.
It seems that the solution obtained with DB is equal to solving only the problem of the first stage (without the subproblems).
Also, it says that the solution found is optimal, however, when I solve the subproblems with the variables of the first stage the solution
is infeasible.

Example

#### Solve with :Extensive

solve_types = [:Dual, :Benders, :Extensive];

# Default parameter file
myparam = "default.txt";

status = solve(modelo, solve_type = solve_types[3], param = myparam)

getobjectivevalue(modelo)

Clp0000I Optimal - objective value 13854.998
13854.997577081438

Var1

#### Solve with :Benders

solve_types = [:Dual, :Benders, :Extensive];

# Default parameter file
myparam = "default.txt";

status = solve(modelo, solve_type = solve_types[2], param = myparam)

getobjectivevalue(modelo)

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 1.51
Solving Nodes      : 1
Primal Bound       : +1.38358758615197e+04 (1 solutions)
Dual Bound         : +1.38358758615197e+04
Gap                : 0.00 %
13835.875861519673

var2

##### Solve problem with var in firts stage.

modelo = Model(solver = ClpSolver());

7053.561000201029
Optimal

var3

then var1 is different to var2 and var2 is equal to var3

I'm working with non-numeric indexes in both variables and restrictions, will Julia JuMP not support string indexes?

What I can do?

Thank you
[https://github.com/Esnilg/SES_MEAN.git](url)

**Comment by Esnilg** [comment]
Hi,

I was reviewing the value of the objective function of: BENDER and: EXTENSIVE and I got this:

c'x + E(Q)

Bender : 13835,60 + 0 = 13835,60

Extensive : 8370,60 + 10484,39 = 13854,99

just with the decomposition of bender seems to solve only the master problem.

I do not know what to do

**Comment by kibaekkim** [comment]
Do you have integer variables in the second stage?

**Comment by Esnilg** [comment]
Hello,

The model has some variables integer  in the first stage, in the second stage all the variables are continuous. however I am working with all the relaxed variables.

regards

**Comment by Esnilg** [comment]
Hello,

I was doing other runs and setting the number of iterations,

in BD / DD / ITER_LIM 1000 # Limit of iteration, 

when I solve with EXTENSIVE the objective solution is 
13,864.95

 but when I solve with: BENDERS

   181  +1.386180e+04          Large  +1.385084e+04      0.08    100.00  2443.7
   182  +1.386179e+04          Large  +1.385084e+04      0.08    100.00  2479.4
   183  +1.386178e+04          Large  +1.385084e+04      0.08    100.00  2519.2
   184  +1.386177e+04          Large  +1.385084e+04      0.08    100.00  2557.7
   185  +1.386175e+04          Large  +1.385084e+04      0.08    100.00  2599.6
   186  +1.386174e+04          Large  +1.385084e+04      0.08    100.00  2643.4
   187  +1.386172e+04          Large  +1.385084e+04      0.08    100.00  2688.7
   188  +1.386171e+04          Large  +1.385084e+04      0.08    100.00  2729.2

the solution of the master always decreases but the dual solution never increases. 

also  13,864.95 not in [ +1.386171e+04 , +1.385084e+04]

regards

**Comment by kibaekkim** [comment]
The dual decomposition is used for getting an initial lower bound for the Benders decomposition. What you saw is the dual decomposition solution and its behavior. It is not really significant to have a good lower bound for the Benders decomposition. My quick suggestion is to set the parameter value to a small number, say 5 or 10.

FYI, the decrease of the master objective is the right behavior in the dual decomposition. It is also possible that you see the dual objective does not change for a number of iterations. 

If you can point out the location of your problem, I can try running it.

**Comment by Esnilg** [comment]
Hello thank you very much, I did what you suggested and the solution I get is not equal to the solution of the extended form. The code is in this address  https://github.com/Esnilg/PROYECTO.git  , I'm using ses_main.jl to run version 3. 

you can try modifying Min to Max in @objective (blk,: Min, TotalCoststoch)
and solve by bender and extended and compare the obtained solutions.

Thank you

**Comment by kibaekkim** [comment]
@Esnilg what are var1, var2, and var3 for? What is your question for this issue?

**Comment by Esnilg** [comment]
Hello, the problem was related to the optimal solution and the decision variable of the first stage, which was not feasible for the second stage, but it was solved in the issue #32
