### ISSUE TITLE
seg fault with runDSP --soln

### ISSUE THREAD

**Issue by gnowzil** [Argonne-National-Laboratory/DSP#33]
runDSP segfaults when running either deterministic equivalent form or Benders decomposition with the option `--soln`.  

`env->solver_->getDualSolution()` returns 0 in getDualSolution in DspCInterface.cpp leading to the segfault when the copy is attempted.

**Comment by kibaekkim** [comment]
I modified the code not to write the dual solution for the Benders, which might not be the best fix. But, it should work.
