### ISSUE TITLE
Implementation request: Printing standard deviation together with objective value

### ISSUE THREAD

**Issue by jyg1124** [Argonne-National-Laboratory/DSP#37]
The standard deviation of the recourse problem is defined as follows.
![image](https://user-images.githubusercontent.com/19360543/46734461-3e93c100-ccce-11e8-90e4-ba337f4a272c.png)

This can be easily calculated after getting the first and second stage solutions.

**Comment by kibaekkim** [comment]
no plan to implement this for now
