### ISSUE TITLE
When using --algo de, only 1 thread is used.

### ISSUE THREAD

**Issue by jyg1124** [Argonne-National-Laboratory/DSP#38]
CPLEX inherently supports multi-threading. But when we want to solve an SMPS instance with 'runDsp --algo de', the CPLEX is running only with a single thread.  

It is looking like the CPLEX parameter CPXPARAM_Threads is set to be 1 inside DSP codes.

**Comment by kibaekkim** [comment]
You can change the parameter value (see https://github.com/Argonne-National-Laboratory/DSP/blob/master/src/Solver/Deterministic/DeDriver.cpp#L128).
