### ISSUE TITLE
cmake issues

### ISSUE THREAD

**Issue by Tdub1229** [Argonne-National-Laboratory/DSP#40]
-- The system information: Linux-4.18.0-25-generic.x86_64
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
CMake Error at UserConfig.cmake:13 (message):
  Please complete the user-specific settings in UserConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ed/anl/DSP/build/CMakeFiles/CMakeOutput.log".
See also "/home/ed/anl/DSP/build/CMakeFiles/CMakeError.log".

**Comment by kibaekkim** [comment]
As said in the message
```
Please complete the user-specific settings in UserConfig.cmake
```
you need to set the paths to some libraries in the file `UserConfig.cmake`.
