### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by mlangiu** [Argonne-National-Laboratory/DSP#42]
I am trying to build DSP on a Mac, but am having issues with MPI.

I followed the steps in PREREQUISITES.md and INSTALL.md and installed mpich 3.3.2 via brew which seems to be recognized according to the cmake output.
However I am getting 
`.../DSP/src/Utility/DspMpi.h:43:3: error: use of undeclared identifier 'MPI'`
and a couple of similar errors from that file and finally
```
In file included from /Users/admin/DSP/src/Solver/DantzigWolfe/DwBranchInt.cpp:10:
In file included from /Users/admin/DSP/src/Solver/DantzigWolfe/DwBranchInt.h:11:
In file included from /Users/admin/DSP/src/Solver/DantzigWolfe/DwBranch.h:11:
In file included from /Users/admin/DSP/src/Solver/DantzigWolfe/DwModel.h:11:
In file included from /Users/admin/DSP/src/TreeSearch/DspModel.h:14:
In file included from /Users/admin/DSP/src/Solver/DecSolver.h:22:
/Users/admin/DSP/src/Utility/DspParams.h:12:10: fatal error: 'tr1/unordered_map' file not found
```
Attached you find my cmake logs
[CMakeError.log](https://github.com/Argonne-National-Laboratory/DSP/files/3908384/CMakeError.log)
[CMakeOutput.log](https://github.com/Argonne-National-Laboratory/DSP/files/3908385/CMakeOutput.log)

**Comment by kibaekkim** [comment]
It looks like you are using `LLVM` compiler, which is a default one on Mac. Please try to compile the code with GNU compilers (e.g., gcc, g++). If you are not sure which is being used now, you can try `gcc -v` in the command line.

The other error message looks related to LAPACK. But, let's try GNU compiler first.

**Comment by mlangiu** [comment]
Thank you for the quick reply!
I am indeed using LLVM, but have gcc at my disposal. It may take me some time to try this, but I will get to it as soon as I can.

**Comment by kibaekkim** [comment]
Now `master` branch should be able to support `llvm`.
