### ISSUE TITLE
Is SCIP required for Benders Decomposition?

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#44]
Hi,

I am using Benders decomposition in DSP with CPLEX 12.9 installed. I got following error:
`Benders decomposition has been disabled because SCIP was not available.
Error: Null solver pointer.`
Is SCIP required for Benders Decomposition?

**Comment by kibaekkim** [comment]
Yes, the Benders decomposition has been implemented with SCIP only (not with CPLEX).
