### ISSUE TITLE
Dual Decomposition Never Terminates

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#45]
Hi, 

I was trying to solve the problem in attachment using dual decomposition. The upper bound and lower bound were found, which are the same as the optimal value, but dd never terminated.  Any idea why this happens? I appreciate your help.

[Example.zip](https://github.com/Argonne-National-Laboratory/DSP/files/4043061/Example.zip)

**Comment by kibaekkim** [comment]
I can reproduce the strange run with the instance. There must be a bug in the run.

For now you can use `--algo dw`. This option basically runs the same algorithm with the capability of finding a global optimal solution.
