### ISSUE TITLE
 Solver/DecDdMasterDSB.cpp not included

### ISSUE THREAD

**Issue by selwyn-mccracken** [Argonne-National-Laboratory/DSP#5]
Hi,

I get the following error when I try to compile the current master using cmake in the project root folder:

CMake Error at src/CMakeLists.txt:35 (add_library):
  Cannot find source file:
    Solver/DecDdMasterDSB.cpp

Here is the current list of files in the Solver directory

src/Solver
├── DecDdMaster.h
├── DecDdMasterSubgrad.cpp
├── DecDdMasterSubgrad.h
├── DecDdMpi.cpp
├── DecDdMpi.h
├── DecDdPrimalMaster.cpp
├── DecDdPrimalMaster.h
├── DecDdSub.cpp
├── DecDdSub.h
├── DecDe.cpp
├── DecDe.h
├── DecSolver.cpp
├── DecSolver.h
├── DecTssSolver.h
├── StoParam.h
├── TssBd.cpp
├── TssBd.h
├── TssBdSub.cpp
├── TssBdSub.h
├── TssEval.cpp
├── TssEval.h
├── TssSolver.cpp
└── TssSolver.h

Can you please add this file to the repo? Thanks

**Comment by kibaekkim** [comment]
I have added all the relevant files to the repo.

**Comment by selwyn-mccracken** [comment]
Brilliant thanks!
