### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by karan-an-1996** [Argonne-National-Laboratory/DSP#54]
Hi, 

in order to get a bit more familiar with the solver and the smps format I wrote a simple two stage Investment problem for which I have attached the smps files below. However, whenever I try to run the solver it gives me the following error message:
![image](https://user-images.githubusercontent.com/53374467/81044832-538a0380-8eb5-11ea-8801-f68b8bd70a1b.png)

I also runned a few of the example problems in the DSP library but for them everything worked just fine. I guess the mistake has to be somewhere in the .stoch file but I compared my stoch file to some of the example ones but was not able to find the mistake.

[Inv_ex_stoch.txt](https://github.com/Argonne-National-Laboratory/DSP/files/4579455/Inv_ex_stoch.txt)
[Inv_ex_time.txt](https://github.com/Argonne-National-Laboratory/DSP/files/4579456/Inv_ex_time.txt)
[Inv_ex_core.txt](https://github.com/Argonne-National-Laboratory/DSP/files/4579457/Inv_ex_core.txt)

Maybe someone can help.
Regards,
Karan

**Comment by kibaekkim** [comment]
Here is my fix to your `.sto` file:
```
* Inv_ex
STOCH 		Asset Mgt
SCENARIOS
 SC SCEN0001	ROOT	0.5	HORIZON
    X1STOCK	BAL1   -1.25
    X1BONDS	BAL1   -1.1
 SC SCEN0002	ROOT	0.25	HORIZON
    X1STOCK	BAL1   -0.95
    X1BONDS	BAL1   -1.05
 SC SCEN0003	ROOT	0.25	HORIZON
    X1STOCK	BAL1   -1.15
    X1BONDS	BAL1   -1.05
ENDATA
```

FYI, reading smps files has been implemented in [Coin-SMI](https://github.com/coin-or/Smi). I did not check whether your format was valid or not.
