### ISSUE TITLE
Slow convergence of DD, BD reports the wrong solution

### ISSUE THREAD

**Issue by rohitkannan** [Argonne-National-Laboratory/DSP#6]
Hello,

I am trying to solve a two-stage stochastic MIP using DSP and am facing some difficulties in the process.

1. Dual decomposition seems to be much slower than the solution of the deterministic equivalent problem using SCIP. I am unable to solve problems with 25 scenarios or more in a reasonable time using DD. Further, DD often terminates with the status "StoppedMPI". Any tips on speeding up DD and making its solution more reliable is appreciated.

2. Benders decomposition doesn't seem to return the same objective value as the solution of DD and DE although this problem only has continuous recourse decisions.

I've attached the source code for the instance I'm trying to solve.

Thanks,
Rohit
[stochpool1.zip](https://github.com/Argonne-National-Laboratory/DSP/files/246024/stochpool1.zip)

**Comment by kibaekkim** [comment]
Thanks for reporting. I will take a look into that.

**Comment by kibaekkim** [comment]
@rohitkannan I have found and fixed a bug when creating a Benders cut for problems with free variables. I have confirmed that BD and DD give the same solution as DE. Slow DD was also affected by the bug, as DD accelerates solution with Benders-type cut. Please pull the code and confirm you do not see the issue.

**Comment by rohitkannan** [comment]
@kibaekkim I can confirm that the updated versions of BD and DD converge to the same solution as DE for different numbers of scenarios.

Thanks,
Rohit
