### ISSUE TITLE
DD Terminates with StoppedMPI status

### ISSUE THREAD

**Issue by rohitkannan** [Argonne-National-Laboratory/DSP#7]
@kibaekkim I am trying to solve a variant of the problem I posted earlier which includes mixed-binary first-stage variables and continuous second stage variables. Both DE and BD give the correct solution, but DD terminates with the status "StoppedMPI" after a few iterations even for a small number of scenarios.

I've attached the source code for the instance I'm trying to solve.

Thanks,
Rohit

[stochpool1_conts.zip](https://github.com/Argonne-National-Laboratory/DSP/files/271513/stochpool1_conts.zip)

**Comment by kibaekkim** [comment]
@rohitkannan There was a bug for generating Benders optimality cut in DD. I have fixed the bug. I am seeing the correct solution from DD. Thanks!
