### ISSUE TITLE
Update of SCIP version

### ISSUE THREAD

**Issue by bcdandurand** [Argonne-National-Laboratory/DSP#74]
Not important now, but I'm just wondering how important it might be to update the version of SCIP interface used in DSP. The version of SCIP currently required by DSP if I understand correctly is currently 3.1.1, whereas the most recent version of SCIP is 7.0.0.

**Comment by kibaekkim** [comment]
DSP uses SCIP 7 now.

**Comment by bcdandurand** [comment]
When I ran `make` for compiling DSP, I got the following interface related error:

```
[ 85%] Building CXX object src/CMakeFiles/DspObj.dir/SolverInterface/OsiScipSolverInterface.cpp.o
/home/bdandurand/DSP/src/SolverInterface/OsiScipSolverInterface.cpp:292:18: error: no matching function for call to 'SCIPtrySolFree'
        SCIP_CALL_ABORT(SCIPtrySolFree(scip_, &sol, true, true, true, true, &stored));
                        ^~~~~~~~~~~~~~
/home/bdandurand/scipoptsuite-7.0.0/scip/src/scip/def.h:340:44: note: expanded from macro 'SCIP_CALL_ABORT'
                          if( (_restat_ = (x)) != SCIP_OKAY )                                                 \
                                           ^
/home/bdandurand/scipoptsuite-7.0.0/scip/src/scip/scip_sol.h:1278:14: note: candidate function not viable: requires 8 arguments, but 7 were provided
SCIP_RETCODE SCIPtrySolFree(
             ^
1 error generated.
```

**Comment by bcdandurand** [comment]
Or perhaps there is a specific way I needed to build and install SCIP? I used the makefile system only (as opposed to cmake), and one change as of version 7 is that the flag -DNO_CONFIG_HEADER is needed for any third-part code (like DSP) that is using the SCIP header files. I don't know if this need is avoided using cmake perhaps. For now, I'm using DSP without SCIP. I can't use Benders decomposition, but that is not needed now anyway.

**Comment by kibaekkim** [comment]
It seems that `scip/config.h` was not read in your scip build. The file contains the version information. How did you compile `scip`?

**Comment by bcdandurand** [comment]
That file doesn't even appear in the source, except in the form `scip/config.h.in`.

**Comment by kibaekkim** [comment]
Can you report that to scip? I don't know if that is the expected behavior. If so, there may be no way to check the version when it is compiled with makefile system.

**Comment by bcdandurand** [comment]
I compiled using `make` in the scip root directory, setting, for example, 
`SHARED=true make all`
I could never get the `cmake` approach to build successfully.

**Comment by bcdandurand** [comment]
I'm quoting this from the SCIP version 7 CHANGELOG:

```
### Deleted and changed API methods and macros

- The preprocessor macro NO_CONFIG_HEADER now needs to be defined when
  including SCIP header files from a SCIP build or installation that
  has been build via the Makefile-only build system.
```

**Comment by kibaekkim** [comment]
Yes, and one should define `NO_CONFIG_HEADER` when building with the Makefile-only build system, as suggested in their `CHANGELOG`.

**Comment by bcdandurand** [comment]
I think the `CHANGELOG` is saying that the flag `-DNO_CONFIG_HEADER` needs to be inserted into the makefile for DSP during the configuration process; it is defined by default in the SCIP makefile. This is true at least if scip is built using the makefile system only. Not saying I understand the rationale on the part of SCIP. I am wondering how to bring this issue up with SCIP, seeing as they take a complacent view toward the admitted incompatibilities between the libraries that result between the two different systems for building.

**Comment by kibaekkim** [comment]
Ah you are right. I am not sure if that can be automated in DSP cmake.
