### ISSUE TITLE
Solver never terminates for two staged MILP Problem

### ISSUE THREAD

**Issue by karan-an-1996** [Argonne-National-Laboratory/DSP#76]
Hello everyone,

I have been trying to solve a two-stage MILP with the DSP solver. I have been running into some issues, however. **The problem is structured in the following way:**
First Stage: 307 Rows, 221 Cols, 60 Integers
Second Stage: 12438 Rows, 14058 Cols, 6012 Integers
No. of scenarios: 1
The chosen input format is the smps file format.

I tried the dd, dw and de algorithm on the problem but none of the algorithms finds a global solution for the given problem. The de algorithm, however, comes quite close to the solution with a gap of 0.15% but it never terminates the solving process. For the dw algorithm, the solver never exceeds the step initializing subproblems and for the dd algorithm, the solver never gives out anything.

Do you have any ideas why this is the case? I believe I might have problems due to the fact that the solver has some parameters such as the gap set to a very narrow value. Therefore, I was wondering if there might be an option with which I can adjust the gaps at which the algorithm terminates and gives out a solution. Additionally, I was wondering if there is a FLAG option in the solver environment with which the user has the possibility to follow the solving process as well as see where the solver actually terminates. 

It would be really helpful if someone could give me further insights.
Regards,
Karan

**Comment by kibaekkim** [comment]
I believe the solver did not terminate because the termination criteria were not met. I realized that the parameters available for the solver are not well described anywhere. I will try to have a proper documentation soon. Meanwhile, please take a look at the parameters defined in https://github.com/Argonne-National-Laboratory/DSP/blob/master/src/Utility/DspParams.cpp
Some parameter files written for testing are available in `./test`.

For `de` as an example, there is not time limit by default. You can set a value for parameter `DE/WALL_LIM`. Similarly, you can play with optimality gap tolerance.

For the other two methods `dw` and `dd` you can print out more messages by setting parameters so that you should be able to report more information about the solution status.

**Comment by karan-an-1996** [comment]
Hello kabaekkim,

so I have been looking into the DspParams.cpp file as you suggested and as far as I have understood, the DE/WALL_LIM parameter can be set in order to enforce a time limit in the solving process. Does that also work for the DD/WALL_LIM and DW/TIME_LIM parameters?

Additionally, I do not quite understand the concept yet. The DspParams.cpp defines a bunch of parameters and my guess is that we can also set those parameters in the file. But what exactly is the point of the parameter files you are referring to in the test folder? As far as I can see it, one only initializes the model in the test files or am I missing something? Do I really need to initialize parameters other than those defined in the DspParams.cpp file or do I need to write a parameter file where I initialize the parameters defined in the DspParams file? 

Additionally, I do not quite grasp how to print out the messages. I gues what you mean is that by setting parameters I can report more information about the solution status. What parameters are you referring to? Are they also defined in the DspParams.cpp file?

It would be really helpful if you could add a documentation explaining the parameters available.

Thanks a lot for your time!
Karan

**Comment by karan-an-1996** [comment]
With the --param option when running the solver I can add a parameter file and I guess I can include one of the parameter files in the .test folder. However, I am unsure what the correct format of the parameter file should be? Should the parameter file be a .cpp file? I am wondering because the solver returns the message "unable to open parameter file".

**Comment by kibaekkim** [comment]
> Does that also work for the DD/WALL_LIM and DW/TIME_LIM parameters?

Yes for dd and dw.

> But what exactly is the point of the parameter files you are referring to in the test folder?

I would like to give some examples for parameter files.

> As far as I can see it, one only initializes the model in the test files or am I missing something?

Each parameter is initialized by its default value, defined in `DspParams.cpp`. The parameter files set values if one wants to use them other than the default values. For example, the following line in `./test/params_cpx.txt`
```
int DD/ITER_LIM 20
```
sets the maximum number of dual decomposition iterations to 20. By default, it is `MAX_INT_NUM` (a very large number).

> Do I really need to initialize parameters other than those defined in the DspParams.cpp file or do I need to write a parameter file where I initialize the parameters defined in the DspParams file?

You only need to write a parameter file, say `myparam.txt` and set values for some parameters. Then, you can use it by
```
./runDsp --algo dd --smps mymodel --param myparam.txt
```

> What parameters are you referring to? Are they also defined in the DspParams.cpp file?

Yes, you can play with parameters `*/LOG_LEVEL`.

**Comment by kibaekkim** [comment]
> However, I am unsure what the correct format of the parameter file should be?

The format of parameter file is
```
<type> <name> <value>
```
For example,
```
int DD/ITER_LIM 20
```

> Should the parameter file be a .cpp file?

No, a simple text file.

> I am wondering because the solver returns the message "unable to open parameter file".

Probably, the file was not in the right path.

**Comment by karan-an-1996** [comment]
Thank you very much for the detailed explanation! It really helped a lot!

Have a nice day!
Karan
