### ISSUE TITLE
Add Examples in C code

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#79]
Do you think it will be helpful if we provide an example written in C code?

**Comment by kibaekkim** [comment]
yes

**Comment by cheesecakeball** [comment]
Through [commit](https://github.com/Argonne-National-Laboratory/DSP/commit/a67fc4f601104667537446590fb378bdddcc1286). 

Suggestion: Install DspCInterface.h under build/include dictionary.

**Comment by kibaekkim** [comment]
> Suggestion: Install DspCInterface.h under build/include dictionary.

Sure, please do so in your branch.
