### ISSUE TITLE
MPI error: MPI_comm_rank invoked MPI_INIT

### ISSUE THREAD

**Issue by juantorres91** [Argonne-National-Laboratory/DSP#8]
Hi I'm new at StochJump and DSP solver,

I have just instaled the DSP solver in Ubuntu, I'm trying to solve several examples from the SMPS folder. Im using the smps_dd.jl example following the instructions on Readme file.

 Benders Decomposition and the DE are working perfectly, but if I try using DD MPI prompts the next error:

"The MPI_COMM_RANK() function was called before MPI_INIT was invoked"
"This disalowed the MPI standard"

Is that problem related to my MPI version? 

Sincerely,

Juan Torres

**Comment by kibaekkim** [comment]
Are you running the DD with MPI? Something like
```
mpirun -n 2 julia test_dd.jl
```

**Comment by juantorres91** [comment]
Hi, 

Yes, I m solving the problem with mpirun but it doesn't works

**Comment by kibaekkim** [comment]
This might happen if you have multiple MPI libraries. That is, Julia MPI module and DSP may try to use different MPI libraries. Can you check if they are using the same MPI libraries? If you don't know what to do, please send me the messages for each of the followings:
1. ``mpicxx -v``
2. ``Pkg.build("MPI")`` in Julia

**Comment by juantorres91** [comment]
Hi,

I'm sending you the output messages

[output.txt](https://github.com/Argonne-National-Laboratory/DSP/files/380029/output.txt)

**Comment by juantorres91** [comment]
Hi, I tried to install the Package in a different Virtual Machine, but i'm having this proble

![image](https://cloud.githubusercontent.com/assets/20445793/17111856/74bbab3c-5271-11e6-893a-d2ece1a22146.png)

I created the library path as in my bash file, but it doens't find it.

Sincerely, Juan

**Comment by kibaekkim** [comment]
This is certainly due to the library path issue. Please check your library path:
```
echo $LD_LIBRARY_PATH
```
and see if you can find a path to ``libDsp.so``.

**Comment by juantorres91** [comment]
Hi,  thats what the shell prompt:

![image](https://cloud.githubusercontent.com/assets/20445793/17120480/99fbcb4c-529a-11e6-8578-6807784e7ac8.png)

**Comment by kibaekkim** [comment]
Strange. Can you try this in Julia?
```julia
Libdl.find_library(["libDsp"])
```

**Comment by juantorres91** [comment]
I got a null response 

![image](https://cloud.githubusercontent.com/assets/20445793/17120786/a707c82a-529c-11e6-8b00-f29c49e6e635.png)

**Comment by kibaekkim** [comment]
Juan and I has resolved this via Skype call. It seems that the machine has both OpenMPI and MPICH. Julia and DSP tried using different libraries. It has been resolved by temporarily removing OpenMPI library.
