### ISSUE TITLE
Auxiliary columns in decompose() function

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#80]
What is the auxiliary columns in decompose() function? https://github.com/Argonne-National-Laboratory/DSP/blob/8a659f3c3ed29c653d69b40f83dc5a772d65ee37/src/Model/TssModel.cpp#L353

**Comment by kibaekkim** [comment]
Do you mean auxiliary columns? or non-auxiliary columns?

The auxiliary columns can be used for anything. The only implementation in DSP is that one auxiliary column is create in the dual decomposition with Benders to represent the first-stage objective function.
