### ISSUE TITLE
Denserow in TssModel.cpp

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#81]
Why to define the dense row for data read from SMPS files? https://github.com/Argonne-National-Laboratory/DSP/blob/8a659f3c3ed29c653d69b40f83dc5a772d65ee37/src/Model/TssModel.cpp#L431

**Comment by kibaekkim** [comment]
It's used to store the date temporarily in order to combine the core and scenario matrices.

**Comment by cheesecakeball** [comment]
> It's used to store the date temporarily in order to combine the core and scenario matrices.

Why not just use lines [line 480-483](https://github.com/Argonne-National-Laboratory/DSP/blob/8a659f3c3ed29c653d69b40f83dc5a772d65ee37/src/Model/TssModel.cpp#L480)? Is there any difference between the data from Julia and SMPS?

**Comment by kibaekkim** [comment]
By looking at the entire function (i.e., `TssModel::decompose`), the data inputs from Julia and SMPS must be different. In particular, the scenario matrix is constructed from both `rows_core_` and `mat_scen_` for SMPS data, whereas it is constructed from `mat_scen_` only for Julia data (I guess C input more exactly).
