### ISSUE TITLE
Issue with using DW-Gurobi on Mac

### ISSUE THREAD

**Issue by gbyeon** [Argonne-National-Laboratory/DSP#86]
I tried to solve the instances "dcap233_200.cor" and "dcap233_300.cor" with runDsp using Gurobi 9. 'dd' seems to be working great, but 'dw' gives me the following error:

Iteration  0: DW Bound +1.797693e+308, Best Dual +1.602658e+03 (gap Large %), nrows 312, ncols 3900, timing (total 1.29, master 0.00, gencols 1.18), statue 3000
Unexpected solution status: 3013 in DwBundleDual::solveMaster
Exception occurred at /Users/geunyeong/DSP/src/Solver/DantzigWolfe/DwBundleDual.cpp:495
Error code 1 in /Users/geunyeong/DSP/src/Solver/DantzigWolfe/DwMaster.cpp:549
Error code 1 in /Users/geunyeong/DSP/src/Solver/DantzigWolfe/DwBundleDual.cpp:124
Unexpected solution status: 3013. 

When using Cplex instead, I don't see this issue.

**Comment by kibaekkim** [comment]
> Note: @gbyeon ran the test on Mac.

So far, I cannot reproduce this on linux. @cheesecakeball: please take a look into this.
I will see if I can reproduce this on my mac, ONCE I get a gurobi license..

**Comment by kibaekkim** [comment]
OK. I can reproduce this. It looks like a bug.

```
Model has 2400 quadratic objective terms
Coefficient statistics:
  Matrix range     [3e-08, 3e+154]
  Objective range  [1e+00, 1e+00]
  QObjective range [1e-01, 1e-01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [5e+00, 2e+01]
Warning: Model contains large matrix coefficient range
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.
Presolve removed 200 rows and 0 columns
Presolve time: 0.00s
Presolved: 383 rows, 2600 columns, 6109 nonzeros
Presolved model has 2400 quadratic objective terms

Warning: Markowitz tolerance tightened to 0.5
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -8.5803205e+03   0.000000e+00   0.000000e+00      0s
Numeric error: very large primal solution due to numerically bad basis matrix

Stopped in 290 iterations and 0.04 seconds
Numeric error
Unexpected solution status: 3013 in DwBundleDual::solveMaster
Exception occurred at /Users/kibaekkim/Documents/REPOS/DSP/src/Solver/DantzigWolfe/DwBundleDual.cpp:495
Error code 1 in /Users/kibaekkim/Documents/REPOS/DSP/src/Solver/DantzigWolfe/DwMaster.cpp:549
Error code 1 in /Users/kibaekkim/Documents/REPOS/DSP/src/Solver/DantzigWolfe/DwBundleDual.cpp:124
Unexpected solution status: 3013.
```

@gbyeon FYI, you can print out more messages with `--param myparams.txt` argument, where the file `myparams.txt` contains
```
int LOG_LEVEL 3
int DW/MASTER/SOLVER/LOG_LEVEL 3
```
