### ISSUE TITLE
Implementing the data structure for MIQP

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#94]
**DeDrive.cpp** [Done]
1. Rewrite writeMps() function by using that defined in DspOsi()

**DspCInterface.h & DspCInterface.cpp** [Done]
1. Add loadQuadraticFirstStage()
2. Add loadQuadraticSecondStage()
commit 1d7cf9f
Question: Better to modify loadFirstStage() and loadSecondStage() instead of writing new functions?

**DecTssModel.h & DecTssModel.cpp** [Done]
1. Overload getFullModel() with quadratic objectives
2. Overload decompose() with quadratic objectives
To do: copySubprob(); copyRecoprob()

**TssModel.h & TssModel.cpp** [Done]
1. Overload loadFirstStage()
2. Overload loadSecondStage()

~~Perform unit test [In progress]~~

**Comment by kibaekkim** [comment]
@cheesecakeball

- Assuming that `writeMps` is not critical for running the algorithm, I suggest to create a separate issue for that.

> Question: Better to modify loadFirstStage() and loadSecondStage() instead of writing new functions?

- Modification may break the existing functionalities. So, in general, addition is preferred over modification.

- What do you mean by `Reload`?

**Comment by cheesecakeball** [comment]
> @cheesecakeball
> 
> * Assuming that `writeMps` is not critical for running the algorithm, I suggest to create a separate issue for that.
> * I also suggest to create a separate issue for the interface.
> 
> > Question: Better to modify loadFirstStage() and loadSecondStage() instead of writing new functions?
> 
> * Modification may break the existing functionalities. So, in general, addition is preferred over modification.
> * What do you mean by `Reload`?

It should be 'overload'. I did not modify the existing functions, but add some additional ones.

**Comment by kibaekkim** [comment]
I opened a separate issue for unit test.
