### ISSUE TITLE
Segment fault in dev/miqp branch, when using SCIP to solve BD

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#97]
[Line 373](https://github.com/Argonne-National-Laboratory/DSP/blob/74836afe21f5f9e35fc5c81acb08846abfb33517/src/DspCInterface.cpp#L373) causes a segment fault. I changed it into line 374 to resolve the segment fault. I have not figured out why this happens.

**Comment by kibaekkim** [comment]
Does this segfault come from your branch for qp?

**Comment by cheesecakeball** [comment]
Yes, it is. When using CPLEX and Gurobi, things are fine. This segment fault only happens when using SCIP.

**Comment by cheesecakeball** [comment]
I still have not figured out why this happens. I will push the code once I fix it.

**Comment by cheesecakeball** [comment]
fixed through 4c2fd721977be341faf6853c1b07b92553f327b5
