### ISSUE TITLE
Implementing the dual decomposition of MIQP

### ISSUE THREAD

**Issue by cheesecakeball** [Argonne-National-Laboratory/DSP#98]
Task 1. [Done] Solve subproblems with quadratic objectives, and solve the problem without Benders cuts
To modify the construction of the scenario subproblem:
 - [x] Modified the subproblems by adding quadratic objective terms [DdSub.cpp & DdSub.h]
 - [x] Modified the upper bounding problem [DdWorkerUB.cpp & DdWorkerUB.h]

- [x] `dev/miqp` can solve dual decomposition of TSSMIQP without Benders cuts 
- [x] Fixed the Gurobi tests in the master branch.

**Comment by kibaekkim** [comment]
@cheesecakeball I see Task 1 in this issue is done by now. Maybe you can open a separate issue for Task 2. Or at least change the title of this issue.
